# Generated by Django 2.2.8 on 2020-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teach_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
